// Generated by https://quicktype.io

export interface Patients {
    userId:      string;
    nutriCodigo: NutriCodigo;
}

export interface NutriCodigo {
    id:             string;
    sexo:           string;
    birthDate:      string;
    nombre:         string;
    createdAt:      string;
    updatedAt:      string;
    alturaPaciente: string;
    doctor:         Doctor;
    avances:        Avance[];
    registros:      Registro[];
    meta:           Meta;
    ejercicio:      Ejercicio[];
}

export interface Avance {
    id:             string;
    observacion:    string;
    createdAt:      string;
    updatedAt:      string;
    peso:           Peso;
    circunferencia: Circunferencia;
    indice:         Indice;
    pliegue:        Pliegue;
}

export interface Circunferencia {
    avanceId:     string;
    femoral:      string;
    biestiloideo: string;
    cuello:       string;
    cintura:      string;
    cadera:       string;
    brazo:        string;
    pierna:       string;
}

export interface Indice {
    avanceId:     string;
    masaCorporal: string;
    masaGrasa:    string;
    masaMagra:    string;
    masaOsea:     string;
    masaResidual: string;
    masaMuscular: string;
}

export interface Peso {
    avanceId: string;
    peso:     string;
}

export interface Pliegue {
    avanceId:         string;
    tricipital:       string;
    pectoral:         string;
    bicipital:        string;
    suprailiaca:      string;
    subescupular:     string;
    pantorrillaMedia: string;
    abdominal:        string;
    musloMedio:       string;
    midaxilar:        string;
}

export interface Doctor {
    id:              string;
    name:            string;
    userType:        string;
    fathersLastName: string;
    mothersLastName: string;
    email:           string;
    sex:             string;
    birthDate:       string;
    phoneNumber:     string;
}

export interface Ejercicio {
    id:        string;
    createdAt: string;
    updatedAt: string;
    exercises: string;
    time:      number;
}

export interface Meta {
    expedienteId: string;
    pesoMeta:     string;
    fechaMeta:    string;
}

export interface Registro {
    id:             string;
    createdAt:      string;
    questionOne:    boolean;
    questionTwo:    string;
    questionThree:  number;
    questionFour:   boolean;
    questionFive:   boolean;
    questionSix:    boolean;
    questionSeven:  boolean;
    questionEight:  boolean;
    questionNine:   boolean;
    questionTen:    boolean;
    questionEleven: boolean;
    questionTwelve: boolean;
}
